<a href="https://colab.research.google.com/github/amoghsalaskar/mltraining/blob/master/GaussianNB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd

In [6]:
#dataset reading
data = pd.read_csv('car.csv')
print(data.shape)
data.head(10)

(10, 5)


Sr. No.   color    type    origin stolen 
0        1     red  sports  domestic     yes
1        2     red  sports  domestic      no
2        3     red  sports  domestic     yes
3        4  yellow  sports  domestic      no
4        5  yellow  sports  imported     yes
5        6  yellow     SUV  imported      no
6        7  yellow     SUV  imported     yes
7        8  yellow     SUV  domestic      no
8        9     red     SUV  imported      no
9       10     red  sports  imported     yes

In [ ]:
# Assigning features and label variables

In [7]:
# Import LabelEncoder
from sklearn import preprocessing

In [8]:
#creating labelEncoder
le = preprocessing.LabelEncoder()

In [10]:
# Assigning features and label variables
color = ['red', 'red', 'red', 'yellow', 'yellow', 'yellow', 'yellow', 'yellow', 'red', 'red']

In [11]:
#Converting string labels into numbers
color_encoded = le.fit_transform(color)

In [12]:
print(color_encoded)

[0 0 0 1 1 1 1 1 0 0]


In [13]:
type = ['sports', 'sports', 'sports', 'sports', 'sports', 'SUV', 'SUV', 'SUV', 'SUV', 'sports']
origin = ['domestic', 'domestic', 'domestic', 'domestic', 'imported', 'imported', 'imported', 'domestic', 'imported', 'imported']
stolen = ['yes', 'no', 'yes', 'no', 'yes', 'no', 'yes', 'no', 'no', 'yes']

In [14]:
type_encoded = le.fit_transform(type)

In [15]:
print(type_encoded)

[1 1 1 1 1 0 0 0 0 1]


In [16]:
origin_encoded = le.fit_transform(origin)

In [17]:
stolen_encoded = le.fit_transform(stolen)

In [18]:
print(origin_encoded)

[0 0 0 0 1 1 1 0 1 1]


In [19]:
print(stolen_encoded)

[1 0 1 0 1 0 1 0 0 1]


In [20]:
color_encoded=le.fit_transform(color)
label=le.fit_transform(stolen)
print("Color:",color_encoded)
print("Stolen:",label)

Color: [0 0 0 1 1 1 1 1 0 0]
Stolen: [1 0 1 0 1 0 1 0 0 1]


In [21]:
type_encoded=le.fit_transform(type)
label=le.fit_transform(stolen)
print("Type:",type_encoded)
print("Stolen:",label)

Type: [1 1 1 1 1 0 0 0 0 1]
Stolen: [1 0 1 0 1 0 1 0 0 1]


In [22]:
origin_encoded=le.fit_transform(origin)
label=le.fit_transform(stolen)
print("Origin:",origin_encoded)
print("Stolen:",label)

Origin: [0 0 0 0 1 1 1 0 1 1]
Stolen: [1 0 1 0 1 0 1 0 0 1]


In [24]:
#Combinig color, type, and origin into single list of tuples
def merge(color_encoded, type_encoded, origin_encoded):
  merged_list=tuple(zip(color_encoded, type_encoded, origin_encoded))
  return merged_list

In [25]:
print(merge(color_encoded, type_encoded, origin_encoded))

((0, 1, 0), (0, 1, 0), (0, 1, 0), (1, 1, 0), (1, 1, 1), (1, 0, 1), (1, 0, 1), (1, 0, 0), (0, 0, 1), (0, 1, 1))


In [26]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

In [27]:
#Create a Gaussian Classifier
model = GaussianNB()

In [28]:
#Train model using the training sets
model.fit(merge(color_encoded, type_encoded, origin_encoded), label)

GaussianNB(priors=None, var_smoothing=1e-09)

In [29]:
#Predict Output
predicted= model.predict([[0,0,1]])
print("Preddicted Value:", predicted)

Preddicted Value: [0]
